### ISSUE TITLE
PNG images have a black background (no transparency)

### ISSUE THREAD

**Issue by AliNear** [3b1b/manim#1436]
### Description
When trying do display a png image(with transparent background), it shows the background as black, didn't encouter the issue when trying with the cairo renderer.

**Code**:
```python
  img = ImageMobject("./dice.png")
  self.play(FadeIn(img))
```

### Results
<img width="626" alt="result" src="https://user-images.githubusercontent.com/38077008/110259231-7639ec80-7f9e-11eb-898a-c0cf5757de5d.png">

# Original image
![dice](https://user-images.githubusercontent.com/38077008/110259246-8fdb3400-7f9e-11eb-992f-b658762c5830.png)

**Comment by baljeetrathi** [comment]
I am facing this problem as well. Searching on Google yields nothing as everyone says manim supports transparency in PNG images. 

Do we need to load the image differently to get transparency?

Any help here would be appreciated. :)

**Comment by AliNear** [comment]
When trying:
`img.image.show()`, it shows an image with transparency, so the issue must be in the rendering process.

**Comment by PacifiK2460** [comment]
Have you gays been able to make it work?. I've tried all (`img.image.show()`, `self.add(img)`) but it stills have black background.

**Comment by sergiotascon** [comment]
Same problem here. All transparent backgrounds and gradients of PNG images are converted to solid colors :'(

**Comment by ImadABID** [comment]
Colors are changing in some cases :
### Original PNG
![0](https://user-images.githubusercontent.com/40466553/117175209-deeeeb00-adce-11eb-9267-ff28012b89d0.png)

### Results
![res](https://user-images.githubusercontent.com/40466553/117175861-908e1c00-adcf-11eb-8e6a-18c46f9b999e.png)

**Comment by TonyCrane** [comment]
The old version (cairo-backend) support transparent png file, but the new version indeed has this bug. @3b1b , can you take a look at this? :)

**Comment by bachirelkhadir** [comment]
I can confirm that I have the same bug as well.

**Comment by 3b1b** [comment]
Turned out to be a single character fix, which is fixed in https://github.com/3b1b/manim/pull/1541.

**Comment by bachirelkhadir** [comment]
There is still a problem with some images:

```
from manimlib import *

class LoadPng(Scene):
    def construct(self):
        fn = "aapl.png"
        self.add(ImageMobject(fn))
        self.wait()

```

Original appl.png:

![aapl](https://user-images.githubusercontent.com/45081812/122116313-76465580-cdf3-11eb-989d-291eb6191727.png)

Manim output:

![LoadPng](https://user-images.githubusercontent.com/45081812/122116282-6cbced80-cdf3-11eb-81ac-54a010398855.png)

**Comment by 3b1b** [comment]
[This commit](https://github.com/3b1b/manim/commit/be78f5257a772285c96da493deeb8dd71d14f4fc) should fix it, let me know if that works for you.

**Comment by bachirelkhadir** [comment]
Yes it does indeed, thank you!
