### ISSUE TITLE
Mouse Tracking not correctly aligned

### ISSUE THREAD

**Issue by DemyCode** [3b1b/manim#1509]
### Describe the bug
The mouse is not aligned with the point position.
When I try to use the mouse interaction the mouse is off and what is strange is that the extending or reducing the Window gives
different offset for the mouse

**Code**:
```python
class DummyScene(Scene):
  def construct(self):
    dot = Dot()
    dot.add_updater(lambda dot, dt : dot.move_to(self.mouse_point))
```

**Wrong display or Error traceback**:
If you move the mouse you will see that it is off and changing the window size changes the offset
![Screenshot from 2021-05-12 23-15-39](https://user-images.githubusercontent.com/18736443/118045305-09651900-b378-11eb-97ac-3ec300673d4e.png)
![Screenshot from 2021-05-12 23-15-39](https://user-images.githubusercontent.com/18736443/118045297-05d19200-b378-11eb-8bc2-fe4f661cf30d.png)

### Additional information
I also saw that by tweeking the window size you can find a certain width and height where the dot is aligned with the mouse,
That might be a clue.

PS : I am also a begginer in OpenSource / online collaboration

**Comment by widcardw** [comment]
I had the same problem with you, and I tried to resize the window. Maybe 1280x720 is the best size, since here's the definition of `Window` in `manimlib/window.py`:
```python
class Window(PygletWindow):
    ...
    def __init__(self, scene, size=(1280, 720), **kwargs):
        ...
```

**Comment by TonyCrane** [comment]
Is this fixed in #1529 ?

**Comment by 3b1b** [comment]
It's not yet fixed.  On my system at least, things work initially but fail once you resize the window. I can look into this a bit later.

**Comment by TonyCrane** [comment]
> It's not yet fixed. On my system at least, things work initially but fail once you resize the window. I can look into this a bit later.

It also works as you said on my computer. So I just don't resize the window to avoid that.¯\_(ツ)_/¯
